INSERT INTO SITES("ID", "NOME", "NOMEALTERADO", "USUARIOALTERACAO") VALUES (1, 'Google', 'Google', '')
INSERT INTO SITES("ID", "NOME", "NOMEALTERADO",  "USUARIOALTERACAO") VALUES (2, 'UOL', 'UOL', '')
INSERT INTO SITES("ID", "NOME", "NOMEALTERADO",  "USUARIOALTERACAO") VALUES (3, 'Estado de Minas', 'Estado de Minas', '')
